CREATE DATABASE Futbol
USE Futbol

CREATE TABLE Stadions
(
Id INT PRIMARY KEY IDENTITY,
Name NVARCHAR(100) NOT NULL,
HourPrice DECIMAL(18,2) NOT NULL CONSTRAINT st_hourPrice_check CHECK (HourPrice>=0),
Capacity INT
)

CREATE TABLE Users
(
Id INT PRIMARY KEY IDENTITY,
Fullname NVARCHAR(70) NOT NULL,
Email NVARCHAR(50) NOT NULL UNIQUE
)

CREATE TABLE Rezarvations
(
Id INT PRIMARY KEY IDENTITY,
StadionId INT NOT NULL CONSTRAINT rezervation_stId FOREIGN KEY REFERENCES Stadions(Id),
UserId INT NOT NULL CONSTRAINT rezervation_usId FOREIGN KEY REFERENCES Users(Id),
StartDate DATETIME2,
EndDate DATETIME2
)